# Description: User Mode Init manager - For TI shared transport
# URL: https://github.com/RobertCNelson/ti-uim
# License: GPLv2

name=ti-uim
version=c738944
release=1
source=(http://mirror.mini-distribution.io/$name-$version.zip)

build() {
	cd $name-$version*

	make CC=$HOST-cc
	make DESTDIR=$PKG install
}
